storage:
  nectar:
    host: server.genomicsresearch.org
    user: eike
    ssh_key: ~/.ssh/nectar
    storage_path: /Backup/Data/Projects/QLD_Genomics/datasets
    build_container: null  # implement later
    encrypt_container: null  # implement later

nodes: # UNIX
  fastq:
    host: local
    user: null
    ssh_key: null  # on runtime machine
    workdir: /data/nanopath/local/fastq # on remote
    nextflow: /home/esteinig/bin/nextflow # on remote
    container: esteinig/pathogen:latest
    pipeline: pathogen
    profile: local
    params:
      illumina: true  # alt config for illumina data
      illumina_tail: _R{1,2}
      bracken_read_length: 100 # bracken config
      bracken_threshold: 0
      bracken_level: S
      databases: # Hot-swap database configurations and resources
        - $HOME/resources/minikraken2 # on remote
        - $HOME/resources/maxikraken # on remote
      database_memory:
        - 8G
        - 80G

reports:
  pathogen:
    database_labels:
      - minikraken2: Minikraken2 (8GB)
      - maxikraken: Maxikraken (60GB)
    database_order:
      - maxikraken
      - minikraken2
    species_flags:
      - Staphylococcus aureus: pathogenic
      - Candida auris: pathogenic
      - Bacillus cereus: poop
      - Homo sapiens: a scourge

netflow:
  flow: fast5 | fastq

server_templates:
  fast5:
    host: local
    user: null
    ssh_key: null  # on runtime machine
    workdir: /data/nanopath/local/fast5 # on remote
    nextflow: /home/esteinig/bin/nextflow # on remote
    container: esteinig/signal:latest
    pipeline: signal
    profile: gpu
    params:
      model: dna_r9.4.1_450bps_hac
      forks: 1
      devices: cuda:0
      runners_per_device: 8
      chunks_per_runner: 1024
      chunk_size: 1000
      num_callers: 8
      guppy_params: -d /models --cpu_threads_per_caller 4
      qcat_params: --trim
      length: 0
      quality: 0
